name: 'Install dependencies'
description: 'install dependencies'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: restore dependencies
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install project dependencies and build
      shell: bash
      run: npm install

    - name: Restore Lumos
      uses: actions/cache@v3
      id: restore_lumos
      with:
        path: 'lumos/packages/*/lib'
        key: ${{ runner.os }}-${{ hashFiles('lumos/packages/*/src') }}

    - name: Build lumos
      if: steps.restore_lumos.outputs.cache-hit != 'true'
      shell: bash
      run: npm run build:lumos
