name: 'Install dependencies'
description: 'install dependencies'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: restore dependencies
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install project dependencies and build
      shell: bash
      run: npm install
