export const MNEMONIC = 'abandon ability able about above absent absorb abstract absurd abuse access accident';
export const USER_NAME = 'xm';
export const PASS_WORD = '1231231231231';
// export const NEXUS_WEB_URL = "https://nexus-e2e.vercel.app/"
export const NEXUS_WEB_URL = 'http://localhost:3000/';
export const NEXUS_WEB_LOCAL_URL = 'http://localhost:3000/';
export const FULL_OWNERSHIP = 'fullOwnership';
export const RULE_BASED_OWNERSHIP = 'ruleBasedOwnership';
export const CKB_RPC = 'https://testnet.ckbapp.dev';
export const NEXUS_BUILD_PATH = './build';
